Next release
TECH7Fox/asterisk-hass-addons pull request #114
Opened 2022-03-09 13:45 UTC by felipecrs

- [ ] Bump version
- [ ] Fix changelog

2022-03-14 19:42 UTC, felipecrs commented
Do we have everything we need for the next release or should we wait for something?

2022-03-15 06:18 UTC, nanosonde commented
The asterisk integration won‘t work anymore.
It will not show the correct extension state.
Also the device[„tech“] is broken. We now only have pjsip endpoints which uses another event „EndpointList“ and has other fields in it, than the the old SIP peer stuff.

2022-03-15 06:27 UTC, nanosonde commented
Opened this issue https://github.com/TECH7Fox/asterisk-hass-integration/issues/49

2022-03-15 07:09 UTC, TECH7Fox commented
Yes, the card and integration work separate. The integration is far from done so I will some work more on it.

As long as the card and add-on work together out of the box, I think we can merge.

2022-03-15 07:33 UTC, TECH7Fox submitted a review, later dismissed

2022-03-15 09:08 UTC, nanosonde commented
Just found a minor issue while reading the logs:
```
[Mar 15 09:03:55] ERROR[476]: loader.c:2508 load_modules: Error loading module 'format_ogg_vorbis.so': libvorbisenc.so.2: cannot open shared object file: No such file or directory
```

Besides the debian package `libvorbis0a` we also have to add `libvorbisenc2` and `libvorbisfile3` as well to the Dockerfile.

2022-03-15 09:26 UTC, nanosonde commented
See PR https://github.com/TECH7Fox/asterisk-hass-addons/pull/120/

2022-03-15 10:14 UTC, nanosonde commented
And a little polish https://github.com/TECH7Fox/asterisk-hass-addons/pull/121

2022-03-15 12:08 UTC, nanosonde commented
I have tested an amd64 images with this PR merged with PR120 and PR121. 
It works good now. Without any error messages.

2022-03-15 12:11 UTC, felipecrs commented
I think we should bump version to 2.0.0.

2022-03-15 12:13 UTC, TECH7Fox commented
I agree. This is a major update.

2022-03-16 00:11 UTC, felipecrs commented
@TECH7Fox please merge if it's good for you. It's good for me.

2022-03-16 07:06 UTC, nanosonde commented
@TECH7Fox @felipecrs 
Let's freeze this branch now and I will manually test this again one more time.
And if it's good let's release it....

2022-03-16 09:07 UTC, nanosonde commented
@TECH7Fox I have tested a local build for amd64 of this current state and it is working on my production system using latest HA-OS, HA core and HA supervisor.

The build was done by using the home assistant addon builder.

So 🟢 from my side!

2022-03-16 09:57 UTC, TECH7Fox requested changes

2022-03-16 09:57 UTC, TECH7Fox commented on asterisk/CHANGELOG.md
> +3. Restore your customizations to the `/etc/config` folder if you have any.
What do you mean with this? Did you mean /config/asterisk?

And maybe add "start the add-on to generate the new config files"?

2022-03-16 09:57 UTC, TECH7Fox commented on repository.yaml
> +maintainer: Jordy Kuhne <jordy.kuhn@gmail.com>
I now see that I missed a 'e'.

```suggestion
maintainer: Jordy Kuhne <jordy.kuhne@gmail.com>
```

2022-03-16 11:11 UTC, felipecrs commented
@TECH7Fox you need to approve the PR before I can merge.

2022-03-16 11:40 UTC, TECH7Fox approved these changes

2022-03-16 11:41 UTC, TECH7Fox commented
Sorry for the wait, currently at work.

2022-03-16 11:42 UTC, felipecrs commented
> Sorry for the wait, currently at work.

No problem :)

2022-03-16 11:43 UTC, merged

2022-03-16 11:43 UTC, felipecrs commented
@nanosonde huuge thanks for your contributions!

2022-03-16 12:03 UTC, TECH7Fox commented
Thanks @nanosonde and @felipecrs for your work! This is awesome. :)

@nanosonde, are you in the discord server?

2022-03-16 14:02 UTC, nanosonde commented
> Thanks @nanosonde and @felipecrs for your work! This is awesome. :)
> 
> @nanosonde, are you in the discord server?

Which dscord server? Never used such a thing. ;-)

BTW: I do not see any new release or new packages for 2.0.0. I did not look at the Github actions, but isn't this done automatically for this repo?

2022-03-18 10:28 UTC, TECH7Fox commented
@nanosonde here is a link: https://discord.gg/qxnDtHbwuD