Add chan_sip on extra port 52xx for dahua and other doorbell support
TECH7Fox/asterisk-hass-addons pull request #199
Opened 2022-12-19 10:42 UTC by bdherouville

2022-12-19 14:45 UTC, felipecrs commented
What's the reason for puttin chan_sip in a different port? Is there any chance it can be used at the same time with pjsip? Example: pjsip for the hass-sip-card and chan_sip for the dahua

2022-12-19 16:49 UTC, felipecrs commented
But my point is: if both can't be enabled at the same time, then there's no need to customize their ports either.

2022-12-19 22:02 UTC, TECH7Fox commented
All looks good to me. @bdherouville set it to ready when you want to merge.

2022-12-20 09:23 UTC, bdherouville commented
Hi @TECH7Fox !
Done. I think the errors are not related to the content I made.

2022-12-20 11:22 UTC, TECH7Fox commented
@bdherouville just need to change the version to `2.4.0` in `asterisk/config.yaml`

2022-12-20 11:59 UTC, bdherouville commented
> @bdherouville just need to change the version to `2.4.0` in `asterisk/config.yaml`

Done, sorry for the closing by mistake. I intially thought I had to close this one to add the config.yaml commit.

2022-12-20 14:02 UTC, TECH7Fox commented
Np. Thanks for the PR.

@felipecrs did you want to test the new version (#190) first?

2022-12-20 14:08 UTC, felipecrs requested changes

2022-12-20 14:08 UTC, felipecrs commented on asterisk/config.yaml
> +version: 2.4.0
You also need to update the CHANGELOG.md

2022-12-20 14:09 UTC, felipecrs commented
> @felipecrs did you want to test the new version (https://github.com/TECH7Fox/asterisk-hass-addons/pull/190) first?

Yes, but I can't test it right now. @bdherouville do you also have a VTO to test v2.3.4 before we merge this? Otherwise I can test it in a few hours.

2022-12-20 14:15 UTC, felipecrs commented on asterisk/CHANGELOG.md
> +- Add chan_sip on ports 52xx, but disabled in modules.conf for dahua vto compatibility (by @bdherouville)
```suggestion
- Add `chan_sip` on ports 52xx, but disabled by default in `modules.conf` for Dahua VTO compatibility (by @bdherouville)
```

2022-12-20 14:16 UTC, bdherouville commented
> > @felipecrs did you want to test the new version (#190) first?
> 
> Yes, but I can't test it right now. @bdherouville do you also have a VTO to test v2.3.4 before we merge this? Otherwise I can test it in a few hours.

Yes, I have a VTO to test, do I have to upgrade my ha module ?

2022-12-20 14:24 UTC, bdherouville commented
> Np. Thanks for the PR.
> 
> @felipecrs did you want to test the new version (#190) first?

Upgrade in progress...

2022-12-20 14:25 UTC, felipecrs commented
Yes, you have to update the Asterisk add-on in your Home Assistant...

2022-12-20 14:26 UTC, felipecrs commented
Just so you know, the new version upgrades Asterisk from 18 to 20. We want to test it because, who knows, maybe they fixed the Dahua issue on the new version.

2022-12-20 15:34 UTC, bdherouville commented
> Just so you know, the new version upgrades Asterisk from 18 to 20. We want to test it because, who knows, maybe they fixed the Dahua issue on the new version.

I tried to convert/implement the PJSIP way of this SIP configuration [https://www.cctvforum.com/topic/48613-dahua-vto2000a-sip-firmware-and-asterisk/?do=findComment&comment=285319](https://www.cctvforum.com/topic/48613-dahua-vto2000a-sip-firmware-and-asterisk/?do=findComment&comment=285319) without success.

2022-12-20 15:42 UTC, felipecrs commented
I guess you should use this? https://tech7fox.github.io/sip-hass-docs/docs/add-on/guides/doorbell#create-pjsip-contact

@TECH7Fox do you know anyone else that has a VTO to help verify that the extension in the link above actually works for a VTO?

2022-12-20 15:54 UTC, TECH7Fox commented
In discord multiple people said that this was working:
```
[8000]
send_rpid=yes
send_pai=yes
from_domain=asterisk
rtp_symmetric=yes
force_rport=yes
rewrite_contact=yes
direct_media=no
context=default
disallow=all
allow=ulaw,alaw,speex,gsm,g726,g723,g722,opus
allow=h264,vp8,vp9
type = endpoint
context = default
;direct_media_method=invite
dtmf_mode=info
callerid="Doorbell" <8000>
;force_rport=no
aors= 8000
auth = auth8000

[8000]
type=aor
max_contacts=6
remove_existing=yes
remove_unavailable=yes
qualify_frequency=0

[auth8000]
type=auth
auth_type=userpass
password=8000         ; Set your password here
username=8000
```
https://discord.com/channels/912636682346582076/996826337727762463/1000507173392105532

2022-12-20 15:55 UTC, TECH7Fox commented
But I think the one in the docs should also worked for VTO.

2022-12-20 16:31 UTC, bdherouville commented
> In discord multiple people said that this was working:
> 
> ```
> [8000]
> send_rpid=yes
> send_pai=yes
> from_domain=asterisk
> rtp_symmetric=yes
> force_rport=yes
> rewrite_contact=yes
> direct_media=no
> context=default
> disallow=all
> allow=ulaw,alaw,speex,gsm,g726,g723,g722,opus
> allow=h264,vp8,vp9
> type = endpoint
> context = default
> ;direct_media_method=invite
> dtmf_mode=info
> callerid="Doorbell" <8000>
> ;force_rport=no
> aors= 8000
> auth = auth8000
> 
> [8000]
> type=aor
> max_contacts=6
> remove_existing=yes
> remove_unavailable=yes
> qualify_frequency=0
> 
> [auth8000]
> type=auth
> auth_type=userpass
> password=8000         ; Set your password here
> username=8000
> ```
> 
> https://discord.com/channels/912636682346582076/996826337727762463/1000507173392105532

Am I supposed to be able to call the doorbell with this configuration ?

2022-12-20 16:32 UTC, TECH7Fox commented
I think so.

2022-12-20 16:56 UTC, bdherouville commented
> I think so.

The link to discord channel redirect me to some landing page saying "no room here".

2022-12-20 17:08 UTC, felipecrs commented
First join the group: https://discord.gg/aYmPHPrQ

2022-12-20 21:25 UTC, bdherouville commented
> First join the group: https://discord.gg/aYmPHPrQ

Despite all my efforts I try to call the VTO but I have this log :

[Dec 20 22:22:30]   == Endpoint 8001 is now Reachable
[Dec 20 22:23:41]     -- Executing [8001@default:1] Progress("PJSIP/7777-00000000", "") in new stack
[Dec 20 22:23:41]     -- Executing [8001@default:2] Ringing("PJSIP/7777-00000000", "") in new stack
[Dec 20 22:23:41]     -- Executing [8001@default:3] Dial("PJSIP/7777-00000000", "PJSIP/8001,50,w") in new stack
[Dec 20 22:23:41]     -- Called PJSIP/8001
[Dec 20 22:23:41]     -- PJSIP/8001-00000001 is ringing
[Dec 20 22:24:12]     -- No one is available to answer at this time (1:0/0/0)
[Dec 20 22:24:12]     -- Auto fallthrough, channel 'PJSIP/7777-00000000' status is 'NOANSWER'

2022-12-20 21:27 UTC, felipecrs commented
I don't understand much of Asterisk but it seems to me that you are calling 7777 instead of calling 8001?

2022-12-20 21:35 UTC, bdherouville commented
> I don't understand much of Asterisk but it seems to me that you are calling 7777 instead of calling 8001? If that's the case, for the sake of testing, I think you should call the VTO directly (supposedly at 8001)

No, I am calling 8001 from 7777.
You can see it here : [Dec 20 22:23:41] -- PJSIP/8001-00000001 is ringing

2022-12-20 22:58 UTC, felipecrs commented
Ok... time to test here too. I will boot up my VTO.

2022-12-20 23:28 UTC, felipecrs commented
WOW! I can't believe it, everything is working!

audio + video through both incoming and outgoing call!

My doorbell is configured like this:

![image](https://user-images.githubusercontent.com/29582865/208785454-986a3048-c76c-4ed3-bd69-8988e75d3ed1.png)

My extension is exactly like this: https://tech7fox.github.io/sip-hass-docs/docs/add-on/guides/doorbell#create-pjsip-contact

For me this is a Xmas Gift!

If someone else can verify it, we won't need chan_sip anymore.

2022-12-22 21:16 UTC, bdherouville commented
Happy Christmas !
It works on my Dahua too!!!

Today I realized that I had a wifi repeater between my sip server and my doorbell.
I did a bit of tcpdump and the result showed that the doorbell was unable to send packets to the SIP server.

I commented the iptables modules that filtered the udp packets and everything workd immediately.

You will find below the tcpdump command that helped my to confirm the diagnostic.

tcpdump -u port 5060

20:54:26.437069 IP 111.222.333.444.5060 > 555.555.555.555.5060: SIP: INVITE sip:8001@555.555.555.555:5060 SIP/2.0
20:54:26.443400 IP 555.555.555.555.5060 > 111.222.333.444.5060: SIP: SIP/2.0 100 Trying
20:54:26.444062 IP 555.555.555.555.5060 > 111.222.333.444.5060: SIP: SIP/2.0 101 Dialog Establishment
20:54:26.451353 IP 555.555.555.555.5060 > 111.222.333.444.5060: SIP: SIP/2.0 180 Ringing
20:54:26.480204 IP 555.555.555.555.5060 > 111.222.333.444.5060: SIP: SIP/2.0 200 OK
20:54:28.474249 IP 555.555.555.555.5060 > 111.222.333.444.5060: SIP: SIP/2.0 200 OK
20:54:32.483895 IP 555.555.555.555.5060 > 111.222.333.444.5060: SIP: SIP/2.0 200 OK
20:54:36.494603 IP 555.555.555.555.5060 > 111.222.333.444.5060: SIP: SIP/2.0 200 OK
20:54:40.503624 IP 555.555.555.555.5060 > 111.222.333.444.5060: SIP: SIP/2.0 200 OK
20:54:44.514301 IP 555.555.555.555.5060 > 111.222.333.444.5060: SIP: SIP/2.0 200 OK
20:54:48.524142 IP 555.555.555.555.5060 > 111.222.333.444.5060: SIP: SIP/2.0 200 OK
20:54:52.534585 IP 555.555.555.555.5060 > 111.222.333.444.5060: SIP: SIP/2.0 200 OK

2022-12-22 22:14 UTC, TECH7Fox commented
Ah, good you got it working.

So we probably don't have to add this anymore? The dahua VTO issue was the only reason to use chan_sip right?

2022-12-22 22:19 UTC, bdherouville commented
Exact !
I bothered you for two uncomented lines in my openwrt wifi extender ... #facepalm

2022-12-22 22:46 UTC, felipecrs commented
This is a great xmas gift from Asterisk team!

2023-02-23 11:33 UTC, TECH7Fox commented
Reopening since there is still interest in chan_sip for older  devices.

2023-03-14 22:43 UTC, TECH7Fox commented
@felipecrs do you know why it can't upload? 

![image](https://user-images.githubusercontent.com/32220029/225158357-3ab35d9f-e7bf-4990-a8b0-1e77498d9c7f.png)

2023-03-14 22:53 UTC, felipecrs commented
It's possible that GitHub has changed their policy for GITHUB_TOKEN. I see some newer workflows have permissions: at the top level declaring the additional permissions it needs. Maybe additional permissions are now needed to publish to ghcr.

2023-03-14 22:57 UTC, felipecrs commented
https://docs.github.com/en/packages/managing-github-packages-using-github-actions-workflows/publishing-and-installing-a-package-with-github-actions#upgrading-a-workflow-that-accesses-ghcrio

2023-03-14 22:58 UTC, felipecrs commented
https://github.com/tech7fox/asterisk-hass-addons/pkgs/container/amd64-addon-asterisk

2023-03-15 00:35 UTC, TECH7Fox commented
I tried some things but I have no idea. Guessing a problem with the home assistant builder?
Anyways enabled bypass for now.

@felipecrs you requested some changes. Were those fixed?

2023-03-15 03:19 UTC, felipecrs commented
I actually don't recall. But it's fine, if it's good for you it's good for me :)

2023-03-15 10:02 UTC, merged

2023-03-15 17:10 UTC, felipecrs commented
After upgrading the add-on, my sip card can't connect to it anymore. The asterisk logs points to "Wrong password" errors.

Do I need to change anything in my configs? I am not trying to use chan_sip, and I didn't change anything in my configs, I just upgraded the add-on.

For now I restored the old version with the backup and it's working again.

2023-03-15 17:14 UTC, pergolafabio commented
Should be no impact? Don't have issues here with pjsip (softphone)

Is chansip loaded? You can just use "noload" in the module file

2023-03-15 19:47 UTC, TECH7Fox commented
Indeed try adding the `noload`. Or delete it to get the new default file again.

2023-03-15 19:48 UTC, felipecrs commented
I'll try it. Thank you!

2023-03-15 20:06 UTC, felipecrs commented
Isn't possible to have two extensions with the same number on both SIP and PJSIP? I thought it is, but if it is not, then we need to handle it indeed. Maybe the extensions in SIP should be generated from 200 instead of 100?

2023-03-15 20:28 UTC, pergolafabio commented
i use both sip and pjsip at same time, should be no issue, just setup with different ports
5060 chansip
5160 pjsip

in dialplan you just do how you the endpoint is registered

like SIP/xxxx or PJSIP/xxx

2023-03-15 20:37 UTC, TECH7Fox commented
Hmm, then I don't know why your endpoints would stop working...

2023-03-15 20:39 UTC, felipecrs commented
I will do some more testing about it. But did someone who had a working setup try to upgrade to confirm if the issue isn't only me?

2023-03-15 20:42 UTC, pergolafabio commented
well, i have no issues at all, but i dont  sip card, only softphones

have you tried the noload for chansip? then it should be the same as before

2023-03-15 20:42 UTC, felipecrs commented
> have you tried the noload for chansip? then it should be the same as before

Will try, but I suppose the goal was to have both working at the same time, right?

2023-03-15 20:49 UTC, pergolafabio commented
yeah, it works for me , i use both at same time with softphones 

i can call from pjsip extension to sip extension and visa versa

2023-03-15 21:56 UTC, felipecrs commented
That did the trick. I resetted my asterisk files and now it works. Thanks!

2023-03-15 22:08 UTC, pergolafabio commented
I think this issue is only for users that started with this addon when chan_sip was still present?

2023-03-15 22:11 UTC, felipecrs commented
I don't think so, because I regularly reset my Asterisk files.